baseURL = '/'
title = 'AgriInsight'
theme = 'hugo-book'

disablePathToLower = true
enableGitInfo = true

[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 1

[menu]
# [[menu.before]]
[[menu.after]]
  name = "Github"
  url = "https://github.com/abidkhan484/AgriInsight"
  weight = 10

[params]
  BookTheme = 'auto'
  BookToC = true
  BookSection = 'docs'
  BookRepo = 'https://github.com/abidkhan484/AgriInsight'
  BookEditPath = 'edit/main/AgriInsight'
  BookDateFormat = 'January 2, 2006'
  BookSearch = true
  BookComments = true
  BookPortableLinks = true
  BookServiceWorker = true
  BookTranslatedOnly = false
